name: "broken-link-check"
description: "Find broken links, missing images, etc within your HTML."
author: "roc"
branding:
  icon: "anchor"
  color: "purple"
inputs:
  url: # id of input
    description: "Url of site"
    required: true
    default: "https://github.com/roc/link-checker"
  blc_args:
    description: "BLC args"
    required: false
    default: ""
  allow_failures:
    description: "Pass the job even if the link checker finds broken links"
    required: false
    default: false
  output_file:
    description: "Summary output file path"
    default: "blc/out.md"
    required: false

outputs:
  result: # id of output
    description: "Report of links"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.url }}
  env:
    inputs_url: ${{ inputs.url }}
    inputs_allow_failures: ${{ inputs.allow_failures }}
    inputs_blc_args: ${{ inputs.blc_args }}
    inputs_output_file: ${{ inputs.output_file }}
