name: Broken link check with issue creation
on: [push]

jobs:
  brokenLinks:
    runs-on: ubuntu-latest
    name: Check links, Create issue
    steps:
      - name: Check for broken links
        id: link-report
        uses: roc/link-checker@master
        with:
          url: "https://github.com/roc/link-checker"
          # important: https://fooasldn.com/ comes back as BLC_ROBOTS without follow=true
          blc_args: --verbose --exclude github --follow true
          allow_failures: true
          output_file: yeah/blc/out.md

      - name: State outputs
        run: |
          echo "steps.blc"
          echo ${{ steps.blc.outputs.exit_code }}
          echo ${{ steps.blc.outputs.report }}
          echo steps ${{steps}}
          echo ${{steps.link-report.outputs}}
          echo ${{steps.link-report.outputs.report}}
          echo ${{steps.link-report.outputs.exit_code}}

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        if: ${{ steps.link-report.outputs.exit_code != 0 }}
        with:
          title: Link Checker Report for github.com/roc/link-checker
          content-filepath: ${{steps.link-report.outputs.report}}
          labels: report, automated issue
