name: Broken link check
on: [push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: roc/link-checker@master
        with:
          url: "https://github.com/roc/link-checker"
          blc_args: --verbose --exclude github --follow false
          allow_failures: true
      - name: Get the result
        run: |
          echo "steps.link-report.outputs.result:" ${{steps.link-report.outputs.result}}
          echo "cat /tmp/blc/out.md"
          cat /tmp/blc/out.md
          echo "cat ./blc/out.md"
          cat ./blc/out.md
